-- MySQL Script generated by MySQL Workbench
-- Sat Aug 10 16:13:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema controlestoque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controlestoque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controlestoque` DEFAULT CHARACTER SET utf8 ;
USE `controlestoque` ;

-- -----------------------------------------------------
-- Table `controlestoque`.`categoriaCesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`categoriaCesta` (
  `idcategoriaCesta` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `ativo` TINYINT NULL,
  PRIMARY KEY (`idcategoriaCesta`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `controlestoque`.`cestaBasica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`cestaBasica` (
  `idcestaBasica` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NULL,
  `categoriaCesta_idcategoriaCesta` INT NOT NULL,
  PRIMARY KEY (`idcestaBasica`),
  INDEX `fk_cestaBasica_categoriaCesta1_idx` (`categoriaCesta_idcategoriaCesta` ASC),
  CONSTRAINT `fk_cestaBasica_categoriaCesta1`
    FOREIGN KEY (`categoriaCesta_idcategoriaCesta`)
    REFERENCES `controlestoque`.`categoriaCesta` (`idcategoriaCesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `controlestoque`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`produto` (
  `idproduto` INT NOT NULL,
  `ativo` TINYINT NULL,
  `nome` VARCHAR(45) NULL,
  `valor` VARCHAR(45) NULL,
  `quantidade` INT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlestoque`.`endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`endereco` (
  `idendereco` INT NOT NULL auto_increment,
  `rua` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idendereco`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `controlestoque`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`cliente` (
  `idcliente` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `desconto` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `endereco_idendereco` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_endereço_idx` (`endereco_idendereco` ASC),
  CONSTRAINT `fk_cliente_endereco`
    FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `controlestoque`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `controlestoque`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`venda` (
  `idvenda` INT NOT NULL,
  `valorTotal` DECIMAL NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idvenda`),
  INDEX `fk_venda_cliente1_idx` (`cliente_idcliente` ASC) ,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `controlestoque`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `controlestoque`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`usuario` (
  `idusuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `salario` DECIMAL NULL,
  `cargo` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `telefone` VARCHAR(11) NULL,
  `endereco_idendereco` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_endereco1_idx` (`endereco_idendereco` ASC),
  CONSTRAINT `fk_usuario_endereco1`
    FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `controlestoque`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


INSERT INTO `controlestoque`.`usuario` (`nome`, `cpf`, `salario`, `cargo`, `email`, `senha`, `telefone`, `endereco_idendereco`)
VALUES
('João Silva', '12345678901', 2500.00, 'Vendedor', 'joao.silva@example.com', 'senha123', '1234567890', 1),
('Maria Oliveira', '98765432100', 3000.00, 'Gerente', 'maria.oliveira@example.com', 'senha456', '0987654321', 2);

INSERT INTO `controlestoque`.`endereco` (`rua`, `numero`, `bairro`, `cidade`, `estado`, `cep`)
VALUES
('Rua Exemplo', '123', 'Bairro Exemplo', 'Cidade Exemplo', 'mg', '12345-678'),
('Avenida Teste', '456', 'Bairro Teste', 'Cidade Teste', 'sp', '98765-432');

-- -----------------------------------------------------
-- Table `controlestoque`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`fornecedor` (
  `idfornecedor` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `email` VARCHAR(45) NULL,
  `numConta` VARCHAR(45) NULL,
  `agencia` VARCHAR(45) NULL,
  `banco` VARCHAR(45) NULL,
  `endereco_idendereco` INT NOT NULL,
  PRIMARY KEY (`idfornecedor`),
  INDEX `fk_fornecedor_endereco1_idx` (`endereco_idendereco` ASC),
  CONSTRAINT `fk_fornecedor_endereco1`
    FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `controlestoque`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlestoque`.`solicitaCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`solicitaCompra` (
  `idsolicitaCompra` INT NOT NULL,
  `dataEntrega` DATE NULL,
  `quantidade` INT NULL,
  `produto_idproduto` INT NOT NULL,
  `fornecedor_idfornecedor` INT NOT NULL,
  PRIMARY KEY (`idsolicitaCompra`),
  INDEX `fk_solicitaCompra_produto1_idx` (`produto_idproduto` ASC),
  INDEX `fk_solicitaCompra_fornecedor1_idx` (`fornecedor_idfornecedor` ASC),
  CONSTRAINT `fk_solicitaCompra_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `controlestoque`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitaCompra_fornecedor1`
    FOREIGN KEY (`fornecedor_idfornecedor`)
    REFERENCES `controlestoque`.`fornecedor` (`idfornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `controlestoque`.`cestaBasica_has_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`cestaBasica_has_produto` (
  `cestaBasica_idcestaBasica` INT NOT NULL,
  `produto_idproduto` INT NOT NULL,
  PRIMARY KEY (`cestaBasica_idcestaBasica`, `produto_idproduto`),
  INDEX `fk_cestaBasica_has_produto_produto1_idx` (`produto_idproduto` ASC),
  INDEX `fk_cestaBasica_has_produto_cestaBasica1_idx` (`cestaBasica_idcestaBasica` ASC),
  CONSTRAINT `fk_cestaBasica_has_produto_cestaBasica1`
    FOREIGN KEY (`cestaBasica_idcestaBasica`)
    REFERENCES `controlestoque`.`cestaBasica` (`idcestaBasica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cestaBasica_has_produto_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `controlestoque`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlestoque`.`funcionario_has_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`usuario_has_venda` (
  `usuario_idusuario` INT NOT NULL,
  `venda_idvenda` INT NOT NULL,
  PRIMARY KEY (`usuario_idusuario`, `venda_idvenda`),
  INDEX `fk_usuario_has_venda_venda1_idx` (`venda_idvenda` ASC),
  INDEX `fk_usuario_has_venda_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_usuario_has_venda_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `controlestoque`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_venda_venda1`
    FOREIGN KEY (`venda_idvenda`)
    REFERENCES `controlestoque`.`venda` (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlestoque`.`cestaBasica_has_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`cestaBasica_has_venda` (
  `cestaBasica_idcestaBasica` INT NOT NULL,
  `venda_idvenda` INT NOT NULL,
  `quantidade` INT NULL,
  `dataVenda` DATE NULL,
  PRIMARY KEY (`cestaBasica_idcestaBasica`, `venda_idvenda`),
  INDEX `fk_cestaBasica_has_venda_venda1_idx` (`venda_idvenda` ASC),
  INDEX `fk_cestaBasica_has_venda_cestaBasica1_idx` (`cestaBasica_idcestaBasica` ASC),
  CONSTRAINT `fk_cestaBasica_has_venda_cestaBasica1`
    FOREIGN KEY (`cestaBasica_idcestaBasica`)
    REFERENCES `controlestoque`.`cestaBasica` (`idcestaBasica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cestaBasica_has_venda_venda1`
    FOREIGN KEY (`venda_idvenda`)
    REFERENCES `controlestoque`.`venda` (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
